{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "import dash\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "from dash.dependencies import Input, Output\n",
    "import plotly.express as px\n",
    "import pickle #library for importing our machine learning model\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn import preprocessing\n",
    "\n",
    "\n",
    "#load the model from disk\n",
    "loaded_model = pickle.load(open('finalized_model.sav', 'rb'))\n",
    "\n",
    "\n",
    "#load the data from disk\n",
    "loaded_data = pickle.load(open('unnormalized_data.sav', 'rb'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [19/Oct/2021 15:29:33] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:29:33] \"\u001b[37mGET /_dash-layout HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:29:33] \"\u001b[37mGET /_dash-dependencies HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 125, in update_output_div\n",
      "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 336, in fit\n",
      "    return self.partial_fit(X, y)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 369, in partial_fit\n",
      "    X = self._validate_data(X, reset=first_pass,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 420, in _validate_data\n",
      "    X = check_array(X, **check_params)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 598, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py\", line 83, in asarray\n",
      "    return array(a, dtype, copy=False, order=order)\n",
      "ValueError: could not convert string to float: ''\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 125, in update_output_div\n",
      "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 336, in fit\n",
      "    return self.partial_fit(X, y)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 369, in partial_fit\n",
      "    X = self._validate_data(X, reset=first_pass,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 420, in _validate_data\n",
      "    X = check_array(X, **check_params)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 598, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py\", line 83, in asarray\n",
      "    return array(a, dtype, copy=False, order=order)\n",
      "ValueError: could not convert string to float: ''\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 125, in update_output_div\n",
      "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 336, in fit\n",
      "    return self.partial_fit(X, y)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 369, in partial_fit\n",
      "    X = self._validate_data(X, reset=first_pass,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 420, in _validate_data\n",
      "    X = check_array(X, **check_params)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 598, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py\", line 83, in asarray\n",
      "    return array(a, dtype, copy=False, order=order)\n",
      "ValueError: could not convert string to float: ''\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [19/Oct/2021 15:29:33] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 125, in update_output_div\n",
      "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 336, in fit\n",
      "    return self.partial_fit(X, y)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 369, in partial_fit\n",
      "    X = self._validate_data(X, reset=first_pass,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 420, in _validate_data\n",
      "    X = check_array(X, **check_params)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 598, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py\", line 83, in asarray\n",
      "    return array(a, dtype, copy=False, order=order)\n",
      "ValueError: could not convert string to float: ''\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 125, in update_output_div\n",
      "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 336, in fit\n",
      "    return self.partial_fit(X, y)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 369, in partial_fit\n",
      "    X = self._validate_data(X, reset=first_pass,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 420, in _validate_data\n",
      "    X = check_array(X, **check_params)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 598, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py\", line 83, in asarray\n",
      "    return array(a, dtype, copy=False, order=order)\n",
      "ValueError: could not convert string to float: ''\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 125, in update_output_div\n",
      "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 336, in fit\n",
      "    return self.partial_fit(X, y)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 369, in partial_fit\n",
      "    X = self._validate_data(X, reset=first_pass,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 420, in _validate_data\n",
      "    X = check_array(X, **check_params)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 598, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py\", line 83, in asarray\n",
      "    return array(a, dtype, copy=False, order=order)\n",
      "ValueError: could not convert string to float: ''\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [19/Oct/2021 15:29:47] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 125, in update_output_div\n",
      "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 336, in fit\n",
      "    return self.partial_fit(X, y)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 369, in partial_fit\n",
      "    X = self._validate_data(X, reset=first_pass,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 420, in _validate_data\n",
      "    X = check_array(X, **check_params)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 598, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py\", line 83, in asarray\n",
      "    return array(a, dtype, copy=False, order=order)\n",
      "ValueError: could not convert string to float: ''\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 125, in update_output_div\n",
      "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 336, in fit\n",
      "    return self.partial_fit(X, y)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 369, in partial_fit\n",
      "    X = self._validate_data(X, reset=first_pass,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 420, in _validate_data\n",
      "    X = check_array(X, **check_params)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 598, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py\", line 83, in asarray\n",
      "    return array(a, dtype, copy=False, order=order)\n",
      "ValueError: could not convert string to float: ''\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 125, in update_output_div\n",
      "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 336, in fit\n",
      "    return self.partial_fit(X, y)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 369, in partial_fit\n",
      "    X = self._validate_data(X, reset=first_pass,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 420, in _validate_data\n",
      "    X = check_array(X, **check_params)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 598, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py\", line 83, in asarray\n",
      "    return array(a, dtype, copy=False, order=order)\n",
      "ValueError: could not convert string to float: ''\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [19/Oct/2021 15:29:50] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 125, in update_output_div\n",
      "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 336, in fit\n",
      "    return self.partial_fit(X, y)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 369, in partial_fit\n",
      "    X = self._validate_data(X, reset=first_pass,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 420, in _validate_data\n",
      "    X = check_array(X, **check_params)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 598, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py\", line 83, in asarray\n",
      "    return array(a, dtype, copy=False, order=order)\n",
      "ValueError: could not convert string to float: ''\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 125, in update_output_div\n",
      "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 336, in fit\n",
      "    return self.partial_fit(X, y)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 369, in partial_fit\n",
      "    X = self._validate_data(X, reset=first_pass,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 420, in _validate_data\n",
      "    X = check_array(X, **check_params)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 598, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py\", line 83, in asarray\n",
      "    return array(a, dtype, copy=False, order=order)\n",
      "ValueError: could not convert string to float: ''\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 125, in update_output_div\n",
      "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 336, in fit\n",
      "    return self.partial_fit(X, y)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 369, in partial_fit\n",
      "    X = self._validate_data(X, reset=first_pass,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 420, in _validate_data\n",
      "    X = check_array(X, **check_params)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 598, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py\", line 83, in asarray\n",
      "    return array(a, dtype, copy=False, order=order)\n",
      "ValueError: could not convert string to float: ''\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [19/Oct/2021 15:29:54] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 125, in update_output_div\n",
      "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 336, in fit\n",
      "    return self.partial_fit(X, y)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 369, in partial_fit\n",
      "    X = self._validate_data(X, reset=first_pass,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 420, in _validate_data\n",
      "    X = check_array(X, **check_params)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 598, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py\", line 83, in asarray\n",
      "    return array(a, dtype, copy=False, order=order)\n",
      "ValueError: could not convert string to float: ''\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 125, in update_output_div\n",
      "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 336, in fit\n",
      "    return self.partial_fit(X, y)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 369, in partial_fit\n",
      "    X = self._validate_data(X, reset=first_pass,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 420, in _validate_data\n",
      "    X = check_array(X, **check_params)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 598, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py\", line 83, in asarray\n",
      "    return array(a, dtype, copy=False, order=order)\n",
      "ValueError: could not convert string to float: ''\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 125, in update_output_div\n",
      "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 690, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 336, in fit\n",
      "    return self.partial_fit(X, y)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 369, in partial_fit\n",
      "    X = self._validate_data(X, reset=first_pass,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py\", line 420, in _validate_data\n",
      "    X = check_array(X, **check_params)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 598, in check_array\n",
      "    array = np.asarray(array, order=order, dtype=dtype)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py\", line 83, in asarray\n",
      "    return array(a, dtype, copy=False, order=order)\n",
      "ValueError: could not convert string to float: ''\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [19/Oct/2021 15:29:56] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:29:58] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:29:58] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:29:59] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:04] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 128, in update_output_div\n",
      "    new_output = loaded_model.predict(new_input_normalized)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 615, in predict\n",
      "    y = super().predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 333, in predict\n",
      "    X = self._validate_for_predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 465, in _validate_for_predict\n",
      "    X = check_array(X, accept_sparse='csr', dtype=np.float64,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 644, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 96, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 128, in update_output_div\n",
      "    new_output = loaded_model.predict(new_input_normalized)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 615, in predict\n",
      "    y = super().predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 333, in predict\n",
      "    X = self._validate_for_predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 465, in _validate_for_predict\n",
      "    X = check_array(X, accept_sparse='csr', dtype=np.float64,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 644, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 96, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 128, in update_output_div\n",
      "    new_output = loaded_model.predict(new_input_normalized)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 615, in predict\n",
      "    y = super().predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 333, in predict\n",
      "    X = self._validate_for_predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 465, in _validate_for_predict\n",
      "    X = check_array(X, accept_sparse='csr', dtype=np.float64,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 644, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 96, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [19/Oct/2021 15:30:10] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:11] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 128, in update_output_div\n",
      "    new_output = loaded_model.predict(new_input_normalized)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 615, in predict\n",
      "    y = super().predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 333, in predict\n",
      "    X = self._validate_for_predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 465, in _validate_for_predict\n",
      "    X = check_array(X, accept_sparse='csr', dtype=np.float64,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 644, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 96, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 128, in update_output_div\n",
      "    new_output = loaded_model.predict(new_input_normalized)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 615, in predict\n",
      "    y = super().predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 333, in predict\n",
      "    X = self._validate_for_predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 465, in _validate_for_predict\n",
      "    X = check_array(X, accept_sparse='csr', dtype=np.float64,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 644, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 96, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 128, in update_output_div\n",
      "    new_output = loaded_model.predict(new_input_normalized)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 615, in predict\n",
      "    y = super().predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 333, in predict\n",
      "    X = self._validate_for_predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 465, in _validate_for_predict\n",
      "    X = check_array(X, accept_sparse='csr', dtype=np.float64,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 644, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 96, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [19/Oct/2021 15:30:11] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:13] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:17] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:19] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:21] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:23] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:25] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:25] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:26] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 128, in update_output_div\n",
      "    new_output = loaded_model.predict(new_input_normalized)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 615, in predict\n",
      "    y = super().predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 333, in predict\n",
      "    X = self._validate_for_predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 465, in _validate_for_predict\n",
      "    X = check_array(X, accept_sparse='csr', dtype=np.float64,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 644, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 96, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 128, in update_output_div\n",
      "    new_output = loaded_model.predict(new_input_normalized)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 615, in predict\n",
      "    y = super().predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 333, in predict\n",
      "    X = self._validate_for_predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 465, in _validate_for_predict\n",
      "    X = check_array(X, accept_sparse='csr', dtype=np.float64,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 644, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 96, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 1056, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/dash/dash.py\", line 991, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-9-07b60479ca2c>\", line 128, in update_output_div\n",
      "    new_output = loaded_model.predict(new_input_normalized)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 615, in predict\n",
      "    y = super().predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 333, in predict\n",
      "    X = self._validate_for_predict(X)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py\", line 465, in _validate_for_predict\n",
      "    X = check_array(X, accept_sparse='csr', dtype=np.float64,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 72, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 644, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"/Users/janlorenz/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 96, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [19/Oct/2021 15:30:31] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:31] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:33] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:34] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:36] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:38] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:43] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [19/Oct/2021 15:30:47] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    }
   ],
   "source": [
    "app = dash.Dash(__name__)\n",
    "server = app.server\n",
    "app.title = \"PHYS-JA: Heart Disease Screening\"\n",
    "\n",
    "app.layout = html.Div(\n",
    "    children=[\n",
    "        html.Div(\n",
    "            children=[\n",
    "                html.P(children=\"❤️\", className=\"header-emoji\"),\n",
    "                html.H1(\n",
    "                    children=\"PHYS-JA: Heart Disease Screening Tool\", className=\"header-title\"\n",
    "                ),\n",
    "                html.P(\n",
    "                    children=\"Analyze the behavior of avocado prices\"\n",
    "                    \" and the number of avocados sold in the US\"\n",
    "                    \" between 2015 and 2018\",\n",
    "                    className=\"header-description\",\n",
    "                ),\n",
    "            ],\n",
    "            className=\"header\",\n",
    "        ),\n",
    "        html.Div(\n",
    "            children=[\n",
    "                html.Div(\n",
    "                    children=[\n",
    "                        html.Div(children=\"Gender\", className=\"menu-title\"),\n",
    "                        dcc.Dropdown(\n",
    "                            id=\"gender-input\",\n",
    "                            options=[\n",
    "                                {\"label\": \"Male\", \"value\": \"1\"},\n",
    "                                {\"label\": \"Female\", \"value\": \"0\"}\n",
    "                            ],\n",
    "                            value=\"\",\n",
    "                            clearable=False,\n",
    "                            className=\"dropdown\",\n",
    "                        ),\n",
    "                    ]\n",
    "                ),\n",
    "                html.Div(\n",
    "                    children=[\n",
    "                        html.Div(children=\"Age\", className=\"menu-title\"),\n",
    "                        dcc.Input(id='age-input', \n",
    "                                  type='number',\n",
    "                                  min=10,\n",
    "                                  max=150, \n",
    "                                  step=1, \n",
    "                                  value=\"\", \n",
    "                                  className=\"input\",\n",
    "                                 )\n",
    "                    ],\n",
    "                ),\n",
    "                 html.Div(\n",
    "                     children=[\n",
    "                     html.Div(children=\"Chest Pain\", className=\"menu-title\"),\n",
    "                        dcc.Dropdown(\n",
    "                            id=\"pain-input\",\n",
    "                            options=[\n",
    "                                {\"label\": \"Typical angina\", \"value\": \"1\"},\n",
    "                                {\"label\": \"Atypical angina\", \"value\": \"2\"},\n",
    "                                {\"label\": \"Non anginal pain\", \"value\": \"3\"},\n",
    "                                {\"label\": \"Asymptomatic\", \"value\": \"4\"}\n",
    "                            ],\n",
    "                            value=\"\",\n",
    "                            clearable=False,\n",
    "                            className=\"dropdown\",\n",
    "                        ),\n",
    "                    ]\n",
    "                ),\n",
    "                 html.Div(\n",
    "                     children=[\n",
    "                     html.Div(children=\"ECG\", className=\"menu-title\"),\n",
    "                        dcc.Dropdown(\n",
    "                            id=\"ecg-input\",\n",
    "                            options=[\n",
    "                                {\"label\": \"Normal\", \"value\": \"0\"},\n",
    "                                {\"label\": \"ST wave abnormality\", \"value\": \"1\"},\n",
    "                                {\"label\": \"Probable or definite left ventricular hypertrophy\", \"value\": \"2\"},\n",
    "                            ],\n",
    "                            value=\"\",\n",
    "                            clearable=False,\n",
    "                            className=\"dropdown\",\n",
    "                        ),\n",
    "                    ]\n",
    "                ),\n",
    "                html.Div(\n",
    "                    children=[\n",
    "                    html.Div(children=\"Cholesterol\", className=\"menu-title\"),\n",
    "                        dcc.Input(id='cholesterol-input', \n",
    "                                  type='number', \n",
    "                                  step=1,\n",
    "                                  value=\"\", \n",
    "                                  className=\"input\",\n",
    "                                 )\n",
    "                    ],\n",
    "                ),\n",
    "            ],\n",
    "            className=\"menu\",\n",
    "        ),\n",
    "            html.Div(\n",
    "            children=[\n",
    "                html.Div(\n",
    "                    id=\"output-prediction\",\n",
    "                    ),\n",
    "            ],\n",
    "            className=\"wrapper\",\n",
    "        ),\n",
    "    ]\n",
    ")\n",
    "\n",
    "#callback\n",
    "@app.callback(\n",
    "    Output(component_id='output-prediction', component_property='children'),\n",
    "    Input(component_id='gender-input', component_property='value'),\n",
    "    Input(component_id='age-input', component_property='value'),\n",
    "    Input(component_id='pain-input', component_property='value'),\n",
    "    Input(component_id='ecg-input', component_property='value'),\n",
    "    Input(component_id='cholesterol-input', component_property='value')\n",
    ")\n",
    "def update_output_div(gender, age, pain, ecg, cholesterol):\n",
    "    new_input = [age, gender, pain, cholesterol, ecg]\n",
    "    loaded_data.drop(columns = ['Class'], inplace = True, errors = 'ignore')\n",
    "    loaded_values = loaded_data.values\n",
    "    new_values = np.vstack([loaded_values,new_input])\n",
    "    min_max_scaler = preprocessing.MinMaxScaler()\n",
    "    x_scaled = min_max_scaler.fit_transform(new_values)\n",
    "    new_data = pd.DataFrame(x_scaled, columns=loaded_data.columns)\n",
    "    new_input_normalized = new_data.tail(1).to_numpy()\n",
    "    new_output = loaded_model.predict(new_input_normalized)\n",
    "    if new_output==1:\n",
    "        return 'Please do further investigations'\n",
    "    elif new_output==0:\n",
    "        return 'No risk identified from the system'\n",
    "\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app.run_server(debug=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "    html.Div(\n",
    "            children=[\n",
    "                html.Div(\n",
    "                    children=dcc.Graph(\n",
    "                        id=\"price-chart\",\n",
    "                        config={\"displayModeBar\": False},\n",
    "                    ),\n",
    "                    className=\"card\",\n",
    "                ),\n",
    "            ],\n",
    "            className=\"wrapper\",\n",
    "        ),\n",
    "\n",
    "\n",
    "# define input\n",
    "new_input = [57, 1, 4, 131, 0]\n",
    "\n",
    "#Normalisation of input\n",
    "loaded_data.drop(columns = ['Class'], inplace = True, errors = 'ignore')\n",
    "\n",
    "loaded_values = loaded_data.values\n",
    "\n",
    "new_values = np.vstack([loaded_values,new_input])\n",
    "print(new_values)\n",
    "\n",
    "\n",
    "min_max_scaler = preprocessing.MinMaxScaler()\n",
    "x_scaled = min_max_scaler.fit_transform(new_values)\n",
    "new_data = pd.DataFrame(x_scaled, columns=loaded_data.columns)\n",
    "\n",
    "new_input_normalized = new_data.tail(1).to_numpy()\n",
    "\n",
    "\n",
    "# get prediction for new input\n",
    "new_output = loaded_model.predict(new_input_normalized)\n",
    "\n",
    "# summarize input and output\n",
    "print(new_input_normalized, new_output)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
